name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.13.5
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.5
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        run: make build
  publish:
    name: Publish Docker
    runs-on: ubuntu-18.04
    steps:
      - name: Push to Github Packages
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_MARCAT_PACKAGE_TOKEN: ${{ secrets.GH_MARCAT_PACKAGE_TOKEN }}
        run: make docker_gh_push